spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=false&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

## 日志输出
logging:
  level:
    ## 根日志
    root: warn
    ## trace:日志最低级别
    com.deerlili.mp.dao: trace
  ## 日志输出格式
  pattern:
    ## %p:日志级别 %m:具体内容 %n:换行 还有替他的
    console: '%p%m%n'

